name: brain_log
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:

  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_widget_from_html: ^0.14.6
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.6
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  scroll_to_index: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true
